title: Shubhendu chaubey
logo: /assets/img/Cool-and-Beautiful-Nature-desktop-wallpaper-image-2560X1600-1600x1200.jpg

description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
